pipeline{
    parameters{
        choice(name: 'terraformAction',choices: ['apply','destroy'],description: 'Choose your terraform action')
    }

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    agent any

    stages{
        stage('Checkout'){
            steps{
                script{
                    dir("terraform"){
                        git url: 'https://github.com/ManojKRISHNAPPA/SnakeGame.git',branch: 'terraform'
                    }
                }
            }
        }

        stage('Plan'){
            steps{
                sh 'pwd; cd EKS/; terraform init'
                sh 'pwd; cd EKS/; terraform plan -out tfplan'
                sh 'pwd; cd EKS/; terraform show -no-color tfplan > tfplan.txt'
            }
        }

        stage('Approval'){
            steps{
                script{
                    def plan = readFile 'EKS/tfplan.txt'
                    input message: "Do you want to proceed with the Terraform action?",
                    parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
                }
            }
        }

        stage('Apply or Destroy'){
            when {
                expression{
                    return  params.terraformAction == 'apply' || params.terraformAction == 'destroy'
                } 
            }
            steps{
                script{
                    if (params.terraformAction == 'apply'){
                        sh 'pwd; cd EKS/; terraform apply -input=false tfplan'
                    }
                    else if (params.terraformAction == 'destroy'){
                        sh 'pwd; cd EKS/; terraform destroy -auto-approve'
                    }
                }
            }
        }

    }

}